#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

cp system/fluid/blockMeshDict system/blockMeshDict
runApplication -s fluid blockMesh &&
mv constant/polyMesh constant/fluid/

cp system/solid/blockMeshDict system/blockMeshDict
runApplication -s solid blockMesh &&
mv constant/polyMesh constant/solid/

touch channel.foam

runApplication -s solid changeDictionary -region solid -subDict dictionaryReplacement
runApplication -s fluid changeDictionary -region fluid -subDict dictionaryReplacement

#runApplication initAlphaField -region fluid
runApplication -s fluid setFields -region fluid
#runApplication -s solid setFields -region solid

runApplication -s solid renumberMesh -region solid -overwrite
runApplication -s fluid renumberMesh -region fluid -overwrite

runApplication  decomposePar -allRegions

mpirun -oversubscribe -np 10 $(getApplication) -parallel  > log.$(getApplication) 2>&1&


#------------------------------------------------------------------------------
